##### ubuntu 18.04 に python, mysqlをインストールする
##### 右記サイト参考: https://32imuf.com/docker/create-django-env-with-docker-compose-psql-mysql/

# ベースとなるイメージ
FROM ubuntu:18.04

# 途中で何も尋ねないようにする
ENV DEBIAN_FRONTEND=noninteractive

#### 基本的なパッケージのインストール
RUN apt-get clean && apt-get update && apt-get install -y \
  vim \
  wget \
  && rm -rf /var/lib/apt/lists/*

#### locales をインストールして設定する
RUN apt-get clean && apt-get update && apt-get install -y \
  locales \
  && rm -rf /var/lib/apt/lists/* \
  && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# タイムゾーンに JST を設定
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

#### installation python

# Python ビルドに必要な deb パッケージのインストール
# `libffi-dev`: 3.6 では不要 (?) 、3.7 では必要
RUN apt-get clean && apt-get update && apt-get install -y \
  build-essential \
  python3-dev \
  libsqlite3-dev \
  libreadline6-dev \
  libgdbm-dev \
  zlib1g-dev \
  libbz2-dev \
  sqlite3 \
  tk-dev \
  zip \
  libssl-dev \
  libffi-dev \
  && rm -rf /var/lib/apt/lists/*

# Python をソースファイルからビルドしてインストール
# `make altinstall`: `make install` の代わりに推奨
RUN wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz \
  && tar xf Python-3.8.1.tgz \
  && cd Python-3.8.1 \
  && ./configure --prefix=/opt/python3.8.1 \
  && make \
  && make altinstall

# Python のシンボリックリンクを作成
RUN ln -s /opt/python3.8.1/bin/python3.8 /usr/local/bin/python

# pip のシンボリックリンクを作成
RUN ln -s /opt/python3.8.1/bin/pip3.8 /usr/local/bin/pip

# pip をアップグレード
RUN pip install -U pip

RUN pip install \
  numpy \
  matplotlib \
  pandas \
  pandas-datareader \
  seaborn \
  scikit-learn \
  mysqlclient \
  flake8 \
  autopep8

# mysqlclient のインストールに必要なので、インストールしておく
RUN apt-get clean && apt-get update && apt-get install -y \
  default-libmysqlclient-dev \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get clean && apt-get update && apt-get install -y \
  mysql-client \
  && rm -rf /var/lib/apt/lists/*
