##### ubuntu 18.04 に python, mysqlをインストールする
##### 右記サイト参考: https://32imuf.com/docker/create-django-env-with-docker-compose-psql-mysql/

# ベースとなるイメージ
FROM mysql:5.7

# locales をインストールして設定する
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# タイムゾーンに JST を設定
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

EXPOSE 3306
