version: '3'

services:
  app:
    container_name: app_server_test_1
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ../app:/app
    working_dir: /app
    # command: bash -c "pip install -r requirements.txt && bash"
    tty: true
    networks:
      - app-net
  
  mysql:
    container_name: mysql_server_test_1
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcdefgh
      MYSQL_DATABASE: stock_price_project
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: abcdefgh
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/db/init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
